DECLARE @URL AS VARCHAR(8000)
SET @URL='https://www.tcmb.gov.tr/kurlar/today.xml'
DECLARE @OBJ AS INT
DECLARE @RESULT AS INT

EXEC @RESULT=SP_OACreate 'MSXML2.XMLHttp', @OBJ OUT
EXEC @RESULT=SP_OAMethod @OBJ, 'open', NULL, 'GET', @URL, false

EXEC @RESULT=SP_OAMethod @obj, send, NULL, ''

CREATE TABLE #EKIN (STRXML VARCHAR(MAX))
INSERT INTO #EKIN(STRXML) EXEC @RESULT=SP_OAGetProperty @OBJ, 'responseXML.xml'
 
DECLARE @XML AS XML
SELECT @XML=STRXML FROM #EKIN
SELECT @XML
DROP TABLE #EKIN

--CREATE PROC DOVIZKURLARI_AKTAR
--AS
DECLARE @HDOC AS INT
EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XML


--create TABLE DOVIZKURLARI (DATE_ DATE, UNIT VARCHAR(50), ISIM VARCHAR(100), CURRENCYNAME VARCHAR(100), FOREXBUYING FLOAT, FOREXSELLING FLOAT, BANKNOTEBUYING FLOAT, BANKNOTESELLING FLOAT)

INSERT INTO EXCHANGERATE (DATE_, UNIT, NAME_, CURRENCYNAME, FOREXBUYING, FOREXSELLING, BANKNOTEBUYING, BANKNOTESELLING)
SELECT CONVERT(DATE,GETDATE()) AS DATE_,* FROM OPENXML(@HDOC, 'Tarih_Date/Currency')
WITH
(Unit varchar(50) 'Unit',
Isim varchar(100) 'Isim',
CurrencyName varchar(100) 'CurrencyName',
ForexBuying float 'ForexBuying',
ForexSelling float 'ForexSelling',
BanknoteBuying float 'BanknoteBuying',
BanknoteSelling float 'BanknoteSelling')

SELECT * FROM EXCHANGERATE 